### ISSUE TITLE
Accept config file path and other flags on run command

### ISSUE THREAD

**Issue by fabioDMFerreira** [nanovms/ops-vscode#3]

**Comment by fabioDMFerreira** [comment]
It would be interesting to have forms like https://github.com/microsoft/vscode-extension-samples/tree/main/quickinput-sample that provide more options on executing commands.

For example, on creating an instance it should be possible to mention the port we want to open to allow public access to some application.

The command `Ops: Run with configuration` addresses all configuration options, although we can provide some easy workflows to execute some operations. Users could try the extension without any ops configuration knowledge. We may say that `Ops: Run with configuration` is for advanced users.

**Comment by fabioDMFerreira** [comment]
For building an image, the workflow should allow choosing a different image name and directories to mount.

**Comment by arknable** [comment]
I'm currently fixing this PR
